---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-in-go
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 0
  selector:
    matchLabels:
      name: rest-api-in-go
  template:
    metadata:
      labels:
        name: rest-api-in-go
    spec:
      containers:
      - name: application
        image: "public.ecr.aws/m2n8f2r0/elitenomad"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: DB_PORT
            value: "$DB_PORT"
          - name: DB_HOST
            value: "$DB_HOST"
          - name: DB_PASSWORD
            value: "$DB_PWD"
          - name: DB_TABLE
            value: "$DB_TABLE"
          - name: DB_USERNAME
            value: "$DB_USERNAME"